<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PackageId>com.janoserdelyi.Validation</PackageId>
		<Authors>Janos Erdelyi</Authors>
		<Company>Janos Erdelyi</Company>
		<Product>Validation</Product>
		<Description>Base element used in validations. Not used stand-alone</Description>
		<Version>1.1.0</Version>
		<AssemblyName>com.janoserdelyi.Validation</AssemblyName>
		<RootNamespace>com.janoserdelyi.Validation</RootNamespace>
		<!-- for packaging -->
		<EnablePackageValidation>true</EnablePackageValidation>
		<!-- automatically generate package on build -->
		<!-- <GeneratePackageOnBuild>true</GeneratePackageOnBuild> -->
		<!-- <PackageLicenseExpression>AGPL</PackageLicenseExpression> -->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../README.md" Pack="true" PackagePath="/"/>
		<None Include="../LICENSE" Pack="true" PackagePath="/"/>
	</ItemGroup>

</Project>
